---
.travis.yml:
  secure: "gdyAdrzLWQymKieoE9tB0o3y8Dx+EH0mb6lCK6sgZe3mKGn/gCOEYtiJs2pUNTcHBYGvnSwKu9ajrLBmp4IPJxV2Uc/Wtoj2Dlcb4dV7VHRSA+N/ZYSMNirO/mqwR6ZW94P0mbrwSpYWkx2lxlC9hLvkHdTWBzWajC3i6Khd7h0="
